name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Run Tests
      uses: sersoft-gmbh/xcodebuild-action@v1.3
      with:
        workspace: ResponsiveTextField.xcworkspace
        scheme: ResponsiveTextField
        destination: "platform=iOS Simulator,OS=15.2,name=iPhone 12"
        action: test
        enable-code-coverage: true
    - uses: michaelhenry/swifty-code-coverage@v1.0.0
      with:
        target: ResponsiveTextFieldTests.xctest
        is-spm: false
    - name: Publish to code climate
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: |
          coverage/lcov.info:lcov
